#!/usr/bin/env python3
"""Cleanup orchestrator. Wakes hourly, marks completions, assigns idle boxes.

For each in-flight task:
  - Probe prod tt_lenK mtime; if newer than started_at_mtime → mark completed.

For each idle compute box:
  - Pick the next pending task whose preferred_box matches (or any if local idle).
  - Kick it off in tmux: rsync prod cache → box, remove stale lock.mdb,
    chain.sh K D D (which does main + verify + push with the patched code).
  - Mark task in_progress, record assigned_box and started_at_mtime.

Reads/writes scripts/cleanup_queue.json. Renders scripts/CLEANUP_TODO.md.
Sends a one-line summary to ntfy on each run.
"""

import datetime
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path("/home/nic/proj/hangman2")
QUEUE_PATH = ROOT / "scripts" / "cleanup_queue.json"
TODO_PATH = ROOT / "scripts" / "CLEANUP_TODO.md"
PROD_CACHE = "/opt/dead-letters/cache"
SSH_OPTS = ["-o", "BatchMode=yes", "-o", "ConnectTimeout=15",
            "-o", "UserKnownHostsFile=/home/nic/.ssh/known_hosts_hangman"]
NTFY = "hangman2-compute-nic"


def sh(cmd: str, timeout: int = 30) -> str:
    """Run shell command, return stdout. Errors return empty string."""
    try:
        r = subprocess.run(["bash", "-c", cmd], capture_output=True, text=True, timeout=timeout)
        return r.stdout.strip()
    except Exception:
        return ""


def ssh(host: str, cmd: str, timeout: int = 30) -> str:
    return sh(f"ssh {' '.join(SSH_OPTS)} {host} {cmd!r}", timeout=timeout)


def prod_mtime(k: int, hash_: str) -> int:
    out = sh(f"ssh -o BatchMode=yes hc4-prod 'stat -c %Y {PROD_CACHE}/tt_len{k}_{hash_}/data.mdb 2>/dev/null'")
    try:
        return int(out)
    except (ValueError, TypeError):
        return 0


def box_idle(box: str, queue: dict) -> bool:
    """A box is idle if no precompute is running on it AND no tmux session
    named 'pc' or 'rsyncN' is active."""
    boxes = queue["boxes"]
    if box == "local":
        running = sh("pgrep -x precompute || true")
        tmux_pc = sh("tmux has-session -t pc 2>&1 && echo YES || echo NO")
        rsync_running = sh("tmux ls 2>/dev/null | grep -E '^rsync[0-9]+:' || true")
        return not running and "YES" not in tmux_pc and not rsync_running
    elif box == "ovh1":
        h = boxes["ovh1"]["ssh"]
        running = ssh(h, "pgrep -x precompute || true")
        tmux_pc = ssh(h, "tmux has-session -t pc 2>&1 && echo YES || echo NO")
        rsync_running = ssh(h, "tmux ls 2>/dev/null | grep -E '^rsync[0-9]+:' || true")
        return not running and "YES" not in tmux_pc and not rsync_running
    return False


def kick_off_local(task: dict) -> tuple[bool, int]:
    """Start cleanup task on local. Returns (success, mtime_baseline)."""
    k = task["k"]
    d = task["depth"]
    hash_ = task["hash"]
    sess = f"cleanup_k{k}"
    target_dir = ROOT / "game_cache" / f"tt_len{k}_{hash_}"
    target_dir.mkdir(parents=True, exist_ok=True)
    baseline = prod_mtime(k, hash_)
    # Combined pipeline in one tmux: rsync, rm lock.mdb, chain.sh.
    # chain.sh on local has lock.mdb cleanup + service restart on push.
    cmd = (
        f"cd {ROOT} && "
        f"rsync -a --info=progress2 hc4-prod:{PROD_CACHE}/tt_len{k}_{hash_}/data.mdb "
        f"  game_cache/tt_len{k}_{hash_}/data.mdb && "
        f"rm -f game_cache/tt_len{k}_{hash_}/lock.mdb && "
        f"bash scripts/chain.sh {k} {d} {d}"
    )
    sh(f"tmux new-session -d -s pc -c {ROOT} {cmd!r}")
    sh(f'curl -sd "cleanup START local {task["id"]}" "https://ntfy.sh/{NTFY}" >/dev/null 2>&1 || true')
    return True, baseline


def kick_off_ovh1(task: dict, queue: dict) -> tuple[bool, int]:
    """Start cleanup task on ovh1."""
    k = task["k"]
    d = task["depth"]
    hash_ = task["hash"]
    h = queue["boxes"]["ovh1"]["ssh"]
    target = f"/mnt/data2/game_cache/tt_len{k}_{hash_}"
    baseline = prod_mtime(k, hash_)
    cmd = (
        f"mkdir -p {target} && "
        f"rsync -a nic@38.49.208.110:{PROD_CACHE}/tt_len{k}_{hash_}/data.mdb "
        f"  {target}/data.mdb && "
        f"rm -f {target}/lock.mdb && "
        f"cd /home/nic/hangman2 && "
        f"bash /home/nic/chain.sh {k} {d} {d}"
    )
    ssh(h, f'tmux new-session -d -s pc bash -c "{cmd}"')
    sh(f'curl -sd "cleanup START ovh1 {task["id"]}" "https://ntfy.sh/{NTFY}" >/dev/null 2>&1 || true')
    return True, baseline


def render_md(queue: dict):
    lines = ["# Cleanup TODO", "",
             "Auto-generated by scripts/orchestrate_cleanup.py. Do not edit by hand.",
             "",
             "Each task scrubs stuck `BOUND_LOWER` entries from the old binary by running",
             "`chain.sh K D D` (main + verify + push) at depth D. Target depths chosen to",
             "cover optimal-play game length per `trace_sim --strategy optimal` — anything",
             "deeper is unreachable in real games following hints.",
             "", "## In flight (separately tracked)", ""]
    for f in queue["in_flight"]:
        lines.append(f"- `{f['id']}` — k={f['k']} d={f['depth']} on **{f['box']}** (started {f['started_at_iso']})")
    lines += ["", "## Queue", "",
              "| # | Task | k | depth | minimax | cache | est | box | status | rationale |",
              "|---|------|---|-------|---------|-------|-----|-----|--------|-----------|"]
    for i, t in enumerate(queue["tasks"], 1):
        cache = f"{t['cache_mb']/1024:.1f} GB" if t['cache_mb'] >= 1024 else f"{t['cache_mb']} MB"
        status = t["status"]
        if status == "completed":
            mark = "✅"
        elif status == "in_progress":
            mark = "🔄"
        elif status == "blocked":
            mark = "🚧"
        else:
            mark = "⏳"
        rationale = t.get("rationale", "")[:60]
        lines.append(
            f"| {i} | `{t['id']}` | {t['k']} | {t['depth']} | {t.get('minimax_misses','?')} "
            f"| {cache} | {t['est_minutes']}m | {t['preferred_box']} | {mark} {status} | {rationale} |"
        )
    if queue.get("skipped_already_clean"):
        lines += ["", "## Skipped (already clean for optimal play)", ""]
        for s in queue["skipped_already_clean"]:
            lines.append(f"- {s['id']}: current d={s['current_d']}, minimax={s['minimax']} — {s['note']}")
    TODO_PATH.write_text("\n".join(lines) + "\n")


def main():
    if not QUEUE_PATH.exists():
        print(f"queue not found at {QUEUE_PATH}", file=sys.stderr)
        sys.exit(1)
    queue = json.loads(QUEUE_PATH.read_text())
    changed = False
    summary = []
    now_iso = datetime.datetime.now().isoformat(timespec="seconds")

    # 1. Mark completions: in_progress task → completed if prod mtime advanced
    for t in queue["tasks"]:
        if t["status"] != "in_progress":
            continue
        cur = prod_mtime(t["k"], t["hash"])
        baseline = t.get("started_at_mtime", 0)
        if cur > baseline:
            t["status"] = "completed"
            t["completed_at_iso"] = now_iso
            t["completed_at_mtime"] = cur
            changed = True
            summary.append(f"COMPLETED {t['id']}")

    # 2. For each box, if idle, assign next pending task that prefers it
    for box in ("local", "ovh1"):
        if not box_idle(box, queue):
            continue
        # find next pending task: prefer matching box, fall back to any pending if local
        candidate = None
        for t in queue["tasks"]:
            if t["status"] != "pending":
                continue
            if t["preferred_box"] == box:
                candidate = t
                break
        # local can also pick up tasks preferred for ovh1 if no match (overflow)
        if not candidate and box == "local":
            for t in queue["tasks"]:
                if t["status"] == "pending" and t["cache_mb"] < 30000:  # local can fit ≤30 GB
                    candidate = t
                    break
        if not candidate:
            continue
        ok, baseline = (kick_off_local(candidate) if box == "local"
                        else kick_off_ovh1(candidate, queue))
        if ok:
            candidate["status"] = "in_progress"
            candidate["assigned_box"] = box
            candidate["started_at_iso"] = now_iso
            candidate["started_at_mtime"] = baseline
            changed = True
            summary.append(f"STARTED {candidate['id']} on {box}")

    if changed:
        QUEUE_PATH.write_text(json.dumps(queue, indent=2) + "\n")
    render_md(queue)

    # Summary line
    pending = sum(1 for t in queue["tasks"] if t["status"] == "pending")
    in_progress = sum(1 for t in queue["tasks"] if t["status"] == "in_progress")
    completed = sum(1 for t in queue["tasks"] if t["status"] == "completed")
    msg = f"orchestrator @ {now_iso[-8:]} pending={pending} in_progress={in_progress} done={completed}"
    if summary:
        msg += " | " + "; ".join(summary)
    print(msg)
    if summary:
        sh(f'curl -sd "{msg}" "https://ntfy.sh/{NTFY}" >/dev/null 2>&1 || true')


if __name__ == "__main__":
    main()
